dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: Configure dashboard button arm type
    displayType: switch
    switch:
      command:
        name: setSwitch
        'on': 'on'
        'off': 'off'
        argumentType: string
      state:
        value: switch.value
        valueType: string
        'on': 'type: Arm AWAY'
        'off': 'type: Arm STAY'
    state: null
automation:
  conditions: []
  actions: []
id: partyvoice23922.dscselectswitch
version: 1
