mnmn: fE4b
vid: fca68975-629a-3521-9bb8-b6ae9eaeb4d3
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: contactSensor
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions: []
detailView:
  - component: main
    capability: partyvoice23922.contactstatus
    version: 1
    values: []
    patch: []
  - component: main
    capability: partyvoice23922.zonebypass
    version: 1
    values: []
    patch: []
  - component: main
    capability: refresh
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: partyvoice23922.contactstatus
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: partyvoice23922.zonebypass
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: fca68975-629a-3521-9bb8-b6ae9eaeb4d3
manufacturerName: fE4b
