mnmn: fE4b
vid: e2e6265b-d047-37e7-96c1-6efe76670e52
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: motionSensor
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions: []
detailView:
  - component: main
    capability: partyvoice23922.motionstatus
    version: 1
    values: []
    patch: []
  - component: main
    capability: partyvoice23922.zonebypass
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: partyvoice23922.motionstatus
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: partyvoice23922.zonebypass
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: e2e6265b-d047-37e7-96c1-6efe76670e52
manufacturerName: fE4b
