mnmn: fE4b
vid: b4cc4434-a608-3f6e-aba5-491c2d2f18da
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: smokeDetector
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions: []
detailView:
  - component: main
    capability: partyvoice23922.smokestatus
    version: 1
    values: []
    patch: []
  - component: main
    capability: partyvoice23922.zonebypass
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: partyvoice23922.smokestatus
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: partyvoice23922.zonebypass
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: b4cc4434-a608-3f6e-aba5-491c2d2f18da
manufacturerName: fE4b
