mnmn: fE4b
vid: 8d10f831-582b-33be-9c0a-1e626919c9d9
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: waterSensor
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions: []
detailView:
  - component: main
    capability: partyvoice23922.waterstatus
    version: 1
    values: []
    patch: []
  - component: main
    capability: partyvoice23922.zonebypass
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: partyvoice23922.waterstatus
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: partyvoice23922.zonebypass
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: 8d10f831-582b-33be-9c0a-1e626919c9d9
manufacturerName: fE4b
